-- Insert languages
INSERT INTO
    tbl_language (code, name)
VALUES
    ('en', 'English'),
    ('ru', 'Russian');

-- Insert content types
INSERT INTO
    tbl_content_type (name, title, title_ru, description, parent_id, parent_name)
VALUES
    ('hero', 'Hero', 'Херо', 'Information about our company and who we are.', 0, ''),
    (
        'achievement',
        'Achievements',
        'Достижения',
        'Notable awards and recognitions we have received.',
        0,
        ''
    ),
    ('achievement_text', 'Text management', 'Управление текстом', '', 2, 'achievement'),
    ('achievement_cards', 'Achievement cards', 'Карточки достижений', '', 2, 'achievement'),
    ('gallery', 'Media Gallery', 'Медиагалерея', '', 0, ''),
    ('gallery_text', 'Text management', 'Управление текстом', '', 5, 'gallery'),
    (
        'video',
        'Video upload',
        'Загрузка видео',
        'A collection of videos showcasing our operations and client feedback.',
        5,
        'gallery'
    ),
    ('contents', 'Content categories', 'Разделы контента', '', 0, ''),
    (
        'how_we_work',
        'How We Work',
        'Как мы работаем',
        'An overview of our process and methodology.',
        9,
        'contents'
    ),
    ('mission', 'Our Mission', 'Наша миссия', 'Our core values and goals.', 9, 'contents'),
    ('partner', 'Our Partners', 'Партнёры', 'Details about our trusted business partners.', 0, ''),
    ('partner_text', 'Text management', 'Управление текстом', '', 12, 'partner'),
    ('partner_management', 'Manage partners', 'Управление партнёрами', '', 12, 'partner'),
    (
        'faq',
        'Frequently asked questions',
        'Часто задаваемые вопросы',
        'Answers to common questions.',
        0,
        ''
    ),
    ('footer', 'Footer', 'Футер', '', 0, ''),
    ('contact', 'Contacts', 'Контакты', '', 16, 'footer'),
    ('social_links', 'Social links', 'Социальные ссылки', '', 16, 'footer'),
    ('other', 'Other', 'Другие', '', 0, '');

INSERT INTO
    tbl_content (lang_id, content_type_id, title, slogan, subtitle, description, image_url, video_url, step, active)
VALUES
    (
        2,
        1,
        'Платформа, предназначенная для поиска грузов и транспорта',
        'ЛЕГКО связывайтесь с новыми перевозчиками и клиентами, ЭФФЕКТИВНО управляя существующими партнерами',
        'Революция в грузоперевозках',
        'UNEEXPO - это не просто платформа, это революция в мире грузоперевозок. Как уникальная социальная сеть, специально созданная для бизнеса. UNEEXPO соединяет вас с широкой сетью профессионалов в логистической индустрии. Независимо от того, являетесь ли вы перевозчиком, логистической компанией или отправителем',
        '',
        '',
        0,
        1
    ),
    (
        2,
        3,
        'Наши достижения',
        '',
        '',
        '',
        '',
        '',
        0,
        1
    ),
    (2, 6, 'Загляните в яркий мир UNEEXPO', '', '', '', '', 'https://office.belentlik.tm/index.php/s/YaQaiDGyPLoD8fb/download/UNEEXPO%20Express%20AD.mp4', 0, 1),
    (2, 7, 'https://office.belentlik.tm/index.php/s/YaQaiDGyPLoD8fb/download/UNEEXPO%20Express%20AD.mp4', '', '', '', '', 'https://office.belentlik.tm/index.php/s/YaQaiDGyPLoD8fb/download/UNEEXPO%20Express%20AD.mp4', 0, 1),
    (
        2,
        18,
        'Готовы трансформировать свой бизнес?',
        '',
        'Присоединяйтесь к UNEEXPO сегодня и станьте частью динамической сети, которая меняет отрасль грузоперевозок. Зарегистрируйтесь сейчас и начните свой путь к беспрепятственному сотрудничеству и успеху',
        'Подпишитесь на наши новости',
        '',
        '',
        0,
        1
    ),
    (
        2,
        18,
        'Найти перевозчиков',
        'Предложить транспорт',
        'Автоматический поиск транспорта и проведение торгов на ваш груз',
        'Сэкономьте время и оптимизируйте свой бюджет',
        '',
        '',
        0,
        1
    ),
    (
        2,
        18,
        'Найти груз',
        'Предложить груз',
        'Автоматический поиск грузов для вашего транспорта',
        'Уменьшите холостые пробеги и найдите новых клиентов',
        '',
        '',
        0,
        1
    ),
    (
        2,
        10,
        'Как мы работаем',
        '',
        '',
        'Откройте для себя наш оптимизированный процесс, который обеспечивает эффективность и превосходство на каждом этапе',
        '',
        '',
        0,
        1
    ),
    (
        2,
        10,
        'Размещение заказа',
        '',
        'Клиенты размещают заказы онлайн, указывая детали забора, доставки и тип груза, инициируя процесс',
        '',
        '',
        '',
        1,
        1
    ),
    (
        2,
        10,
        'Планирование маршрута',
        '',
        'Используя передовое программное обеспечение, определяются оптимальные маршруты, учитывающие такие факторы, как расстояние, трафик и приоритеты доставки',
        '',
        '',
        '',
        2,
        1
    ),
    (
        2,
        10,
        'Транспортировка',
        '',
        'Грузы загружаются на соответствующие транспортные средства и отправляются, обеспечивая надлежащее обращение, безопасность и соблюдение графиков доставки',
        '',
        '',
        '',
        3,
        1
    ),
    (
        2,
        10,
        'Отслеживание и мониторинг',
        '',
        'Системы отслеживания в реальном времени контролируют отправления, предоставляя обновления клиентам и позволяя оперативно управлять любыми проблемами',
        '',
        '',
        '',
        4,
        1
    ),
    (
        2,
        10,
        'Доставка и подтверждение',
        '',
        'По прибытии грузы выгружаются, проверяются по сравнению с деталями заказа и получению подтверждения успешной доставки от получателей',
        '',
        '',
        '',
        5,
        1
    ),
    (
        2,
        11,
        'Наша миссия',
        '',
        'В UNEEXPO наша миссия — развивать индустрию грузоперевозок и укреплять связи между бизнесами. Мы обеспечиваем сотрудничество, объединяя логистические компании, перевозчиков и отправителей, предоставляя инструменты для оптимизации операций и расширения глобального охвата.',
        'С UNEEXPO вы не просто присоединяетесь к платформе, а становитесь частью динамичной сети, формирующей будущее грузоперевозок.',
        '',
        '',
        0,
        1
    ),
    (
        2,
        13,
        'Наши надежные партнеры',
        '',
        '',
        'Партнерство с лидерами отрасли для предоставления надежных и эффективных решений в области грузоперевозок по всему миру',
        '',
        '',
        0,
        1
    ),
    (
        2,
        14,
        'C.H. ROBINSON',
        '',
        'Американская транспортная компания, включающая услуги третьей стороны логистики',
        '',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/C._H._Robinson_logo.svg/2560px-C._H._Robinson_logo.svg.png',
        '',
        0,
        1
    ),
    (
        2,
        14,
        'XPO',
        '',
        'Американская транспортная компания, осуществляющая перевозку сборных грузов по Северной Америке',
        '',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/XPO%2C_Inc_%282023%29.svg/2560px-XPO%2C_Inc_%282023%29.svg.png',
        '',
        0,
        1
    ),
    (
        2,
        14,
        'FedEx',
        '',
        'Американский многонациональный конгломерат, ранее известный как Federal Express Corporation',
        '',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/FedEx_Corporation_-_2016_Logo.svg/1200px-FedEx_Corporation_-_2016_Logo.svg.png',
        '',
        0,
        1
    ),
    (
        2,
        15,
        'Я уже использую биржи грузоперевозок, зачем мне нужна еще одна?',
        '',
        'Потому что потому что потому что потому что',
        '',
        '',
        '',
        0,
        1
    ),
    (2, 15, 'Что такое публичная биржа грузоперевозок?', '', 'Это бла бла бла бла бла', '', '', '', 0, 1),
    (
        2,
        15,
        'UNEEXPO - это цифровой экспедитор?',
        '',
        'Более чем, это логистический гигант в Центральной Азии',
        '',
        '',
        '',
        0,
        1
    ),
    (
        2,
        15,
        'Не нашли то, что искали?',
        '',
        'Если у вас остались вопросы и вам нужна дополнительная помощь, мы здесь, чтобы помочь! Пожалуйста, не стесняйтесь обращаться к нашей службе поддержки, и мы будем рады вам помочь',
        'Ваш вопрос',
        '',
        '',
        0,
        1
    ),
    (2, 16, 'Номер телефона', '', '+99361234567', '', '', '', 0, 1),
    (2, 16, 'Почта', '', 'textransportexpedition@gmail.com', '', '', '', 0, 1),
    (2, 16, 'Skype', '', 'live:texlogistics', '', '', '', 0, 1),
    (2, 17, 'Instagram URL link', '', 'https:/www.Instagram.com/logistic_asa', '', '', '', 0, 1),
    (2, 17, 'Linkedin URL link', '', 'https:/www.Linkedin.com/logistic_asa', '', '', '', 0, 1),
    (2, 17, 'TikTok URL link', '', 'https:/www.TikTok.com/logistic_asa', '', '', '', 0, 1),
    (
        1,
        1,
        'A platform designed to coordinate freight transportation',
        'EASILY connect with new carriers and clients, EFFICIENTLY manage existing partners',
        'Revolution in freight transportation',
        'TECH is not just a platform, it is a revolution in the world of freight transportation. As a unique social network specifically designed for business, TECH connects you with a broad network of professionals in the logistics industry. Whether you are a carrier, a logistics company, or a shipper, TECH empowers you to define how and with whom you work.',
        '',
        '',
        0,
        1
    ),
    (
        1,
        3,
        'Our Achievements',
        '',
        '',
        'From our extensive partner network to the innovative solutions we provide, see how TECH is transforming the freight industry.',
        '',
        '',
        0,
        1
    ),
    (1, 6, 'Take a look at the vibrant world of TECH', '', '', '', '', 'https://office.belentlik.tm/index.php/s/YaQaiDGyPLoD8fb/download/UNEEXPO%20Express%20AD.mp4', 0, 1),
    (1, 7, 'https://office.belentlik.tm/index.php/s/YaQaiDGyPLoD8fb/download/UNEEXPO%20Express%20AD.mp4', '', '', '', '', 'https://office.belentlik.tm/index.php/s/YaQaiDGyPLoD8fb/download/UNEEXPO%20Express%20AD.mp4', 0, 1),
    (
        1,
        18,
        'Ready to transform your business?',
        '',
        'Join TECH today and become part of a dynamic network reshaping the freight industry. Sign up now and start your journey towards seamless collaboration and success.',
        'Subscribe to our newsletter',
        '',
        '',
        0,
        1
    ),
    (
        1,
        18,
        'Find Carriers',
        '',
        'Automatic transportation search and bidding for your freight',
        'Save time and optimize your budget',
        '',
        '',
        0,
        1
    ),
    (
        1,
        18,
        'Find Freight',
        '',
        'Automatic freight search for your transport',
        'Reduce idle runs and find new clients',
        '',
        '',
        0,
        1
    ),
    (
        1,
        10,
        'How We Work',
        '',
        '',
        'Discover our streamlined process that ensures efficiency and excellence at every step.',
        '',
        '',
        0,
        1
    ),
    (
        1,
        10,
        'Placing an Order',
        '',
        'Clients place orders online, specifying the pickup, delivery details, and type of freight to initiate the process.',
        '',
        '',
        '',
        1,
        1
    ),
    (
        1,
        10,
        'Route Planning',
        '',
        'Using advanced software, optimal routes are determined, factoring in distance, traffic, and delivery priorities.',
        '',
        '',
        '',
        2,
        1
    ),
    (
        1,
        10,
        'Transportation',
        '',
        'Freights are loaded onto appropriate vehicles and dispatched, ensuring proper handling, safety, and on-time delivery.',
        '',
        '',
        '',
        3,
        1
    ),
    (
        1,
        10,
        'Tracking and Monitoring',
        '',
        'Real-time tracking systems monitor the shipments, providing updates to clients and enabling swift issue management.',
        '',
        '',
        '',
        4,
        1
    ),
    (
        1,
        10,
        'Delivery and Confirmation',
        '',
        'Upon arrival, the freight is unloaded, checked against order details, and confirmation of successful delivery is received from recipients.',
        '',
        '',
        '',
        5,
        1
    ),
    (
        1,
        11,
        'Our Mission',
        '',
        'At TECH, our mission is to advance the freight industry by fostering meaningful connections. We bridge the gap between businesses, enabling seamless communication and collaboration. By bringing together a diverse community of logistics companies, carriers, and shippers, we provide the tools needed to optimize operations and expand global reach.',
        'With TECH, you don’t just join a platform, you become part of a dynamic network shaping the future of global freight.',
        '',
        '',
        0,
        1
    ),
    (
        1,
        13,
        'Our Trusted Partners',
        '',
        '',
        'Partnering with industry leaders to deliver reliable and efficient freight solutions across the globe.',
        '',
        '',
        0,
        1
    ),
    (
        1,
        14,
        'C.H. ROBINSON',
        '',
        'An American transportation company offering third-party logistics services.',
        '',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/C._H._Robinson_logo.svg/2560px-C._H._Robinson_logo.svg.png',
        '',
        0,
        1
    ),
    (
        1,
        14,
        'XPO',
        '',
        'An American transport company handling less-than-truckload freight across North America.',
        '',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/XPO%2C_Inc_%282023%29.svg/2560px-XPO%2C_Inc_%282023%29.svg.png',
        '',
        0,
        1
    ),
    (
        1,
        14,
        'FedEx',
        '',
        'An American multinational conglomerate, formerly known as Federal Express Corporation.',
        '',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/FedEx_Corporation_-_2016_Logo.svg/1200px-FedEx_Corporation_-_2016_Logo.svg.png',
        '',
        0,
        1
    ),
    (
        1,
        15,
        'I already use freight exchanges, why do I need another one?',
        '',
        'Because TECH offers enhanced features, unique opportunities, and a broader network.',
        '',
        '',
        '',
        0,
        1
    ),
    (
        1,
        15,
        'What is a public freight exchange?',
        '',
        'A public freight exchange is an online marketplace where shippers and carriers connect to trade freight services.',
        '',
        '',
        '',
        0,
        1
    ),
    (
        1,
        15,
        'Is TECH a digital freight forwarder?',
        '',
        'More than that, TECH is a logistics giant in Central Asia.',
        '',
        '',
        '',
        0,
        1
    ),
    (
        1,
        15,
        'Didn’t find what you were looking for?',
        '',
        'If you still have questions and need further assistance, we are here to help! Please feel free to reach out to our support team, and we’ll be happy to assist you.',
        'Your question',
        '',
        '',
        0,
        1
    ),
    (1, 16, 'Phone Number', '', '+99361234567', '', '', '', 0, 1),
    (1, 16, 'Email', '', 'textransportexpedition@gmail.com', '', '', '', 0, 1),
    (1, 16, 'Skype', '', 'live:texlogistics', '', '', '', 0, 1),
    (1, 17, 'Instagram URL link', '', 'https:/www.Instagram.com/logistic_asa', '', '', '', 0, 1),
    (1, 17, 'LinkedIn URL link', '', 'https:/www.Linkedin.com/logistic_asa', '', '', '', 0, 1),
    (1, 17, 'TikTok URL link', '', 'https:/www.TikTok.com/logistic_asa', '', '', '', 0, 1);

INSERT INTO
    tbl_content (lang_id, content_type_id, title, slogan, subtitle, description, count, count_type, image_url, video_url, step, active)
VALUES
    (
        2,
        4,
        'Активных Пользователей',
        '',
        '',
        'Присоединяйтесь к растущему сообществу профессионалов',
        20000,
        'number',
        '',
        '',
        0,
        1
    ),
    (
        2,
        4,
        'Автомобильных Перевозок',
        '',
        '',
        'Испытайте эффективность беспрепятственной автомобильной перевозки с UNEEXPO',
        5000,
        'number',
        '',
        '',
        0,
        1
    ),
    (
        2,
        4,
        'Логистических Компаний',
        '',
        '',
        'Сотрудничайте с ведущими логистическими компаниями по всему миру',
        5000,
        'number',
        '',
        '',
        0,
        1
    ),
    (
        2,
        4,
        'Заключенных Сделок',
        '',
        '',
        'Укрепите свой бизнес успешными сделками и партнерствами, заключенными на UNEEXPO',
        50000,
        'number',
        '',
        '',
        0,
        1
    ),
    (
        1,
        4,
        'Active Users',
        '',
        '',
        'Join a growing community of professionals making a difference in the freight industry.',
        20000,
        'number',
        '',
        '',
        0,
        1
    ),
    (
        1,
        4,
        'Freight Shipments',
        '',
        '',
        'Experience the efficiency of seamless freight transport with TECH.',
        5000,
        'number',
        '',
        '',
        0,
        1
    ),
    (
        1,
        4,
        'Logistics Companies',
        '',
        '',
        'Partner with leading logistics companies across the globe.',
        5000,
        'number',
        '',
        '',
        0,
        1
    ),
    (
        1,
        4,
        'Shippers',
        '',
        '',
        'Find reliable shippers who trust TECH for their freight needs.',
        8000,
        'number',
        '',
        '',
        0,
        1
    ),
    (
        1,
        4,
        'Deals Closed',
        '',
        '',
        'Strengthen your business with successful deals and partnerships made on TECH.',
        50000,
        'number',
        '',
        '',
        0,
        1
    );